### ISSUE TITLE
Bug fix and tasks

### ISSUE THREAD

**Issue by samorso** [SMAC-Group/ptds2018_website#2]
- [x] fix bug with Tutorial #1 
- [x] add Tutorial #2
- [x] modification of problem #2 in homework #2
- [x] create homework #4 with R-package, shiny app and Rcpp
